const mongoose = require("mongoose");
const { encrypt, decrypt } = require("../utils/crypto");

const { Schema } = mongoose;

/**
 * ---------------------------------------------------------------------------
 * One document per credential entry. A user can have multiple credentials
 * per channel (e.g. two email inboxes, one WhatsApp number, one SMS
 * provider, several AI provider keys). `channel` decides which sub-object
 * is populated. Secret fields are transparently encrypted at rest using the
 * app-wide AES-256-GCM helper (utils/crypto.js, same ENCRYPTION_KEY already
 * used for bot BYOK keys) via schema-level set/get.
 * ---------------------------------------------------------------------------
 */

const secretField = {
  type: String,
  set: (v) => (v === undefined || v === null || v === "" ? undefined : encrypt(v)),
  get: (v) => (v ? decrypt(v) : v),
};

// ---------- EMAIL ----------
const EmailCredentialSchema = new Schema(
  {
    method: { type: String, enum: ["smtp", "oauth", "api"], required: true },

    fromEmail: { type: String, trim: true, lowercase: true },
    fromName: { type: String, trim: true },

    // --- SMTP ---
    smtp: {
      host: { type: String, trim: true },
      port: { type: Number },
      username: { type: String, trim: true },
      password: secretField,
      encryption: { type: String, enum: ["tls", "ssl", "none"], default: "tls" },
    },

    // --- OAuth2 (Google / Microsoft) — token pasted/obtained via provider consent ---
    oauth: {
      provider: { type: String, enum: ["google", "microsoft"] },
      email: { type: String, trim: true, lowercase: true },
      accessToken: secretField,
      refreshToken: secretField,
      tokenExpiry: { type: Date },
      scope: { type: String },
    },

    // --- Transactional API (SES / SendGrid / Mailgun / Postmark / Resend) ---
    api: {
      provider: { type: String, enum: ["ses", "sendgrid", "mailgun", "postmark", "resend"] },
      apiKey: secretField,
      accessKeyId: secretField, // AWS SES
      secretAccessKey: secretField, // AWS SES
      region: { type: String },
      verifiedDomain: { type: String },
    },
  },
  { _id: false }
);

// ---------- WHATSAPP (Meta Cloud API) ----------
// Two ways a credential gets here, both landing in the same shape:
//
//   "manual"   — the pre-existing paste-your-own-values form. The tenant
//                brings their OWN Meta App (appId/appSecret required),
//                configures the webhook themselves in their App Dashboard,
//                and pastes a token they generated by hand.
//
//   "embedded" — Meta's official WhatsApp Embedded Signup (Facebook Login
//                for Business popup, see services/whatsappEmbeddedSignup.
//                service.js). The tenant's WABA/number is shared with OUR
//                platform's own Meta Tech Provider App (META_APP_ID) —
//                there is no per-tenant App, so appId/appSecret are NOT
//                collected from the user; they're filled in from
//                META_APP_ID/META_APP_SECRET at credential-creation time so
//                the existing appSecret-based webhook signature check in
//                whatsapp.controller.js keeps working unchanged for both
//                methods. Webhook subscription happens automatically via
//                the Graph API (subscribed_apps) as part of the exchange —
//                nothing for the tenant to paste into a dashboard.
const WhatsappCredentialSchema = new Schema(
  {
    signupMethod: { type: String, enum: ["manual", "embedded"], default: "manual" },

    phoneNumber: { type: String, trim: true, required: true },
    phoneNumberId: { type: String, trim: true, required: true },
    wabaId: { type: String, trim: true, required: true },
    businessId: { type: String, trim: true }, // Meta Business Manager ID — only populated for signupMethod: "embedded"
    appId: { type: String, trim: true }, // required for "manual" only — see pre-validate hook below
    appSecret: secretField, // required for "manual" only; auto-filled from META_APP_SECRET for "embedded" — see pre-validate hook below
    accessToken: secretField,
    webhookVerifyToken: secretField, // legacy field, see original comment — unused going forward
    businessVerificationStatus: {
      type: String,
      enum: ["pending", "verified", "rejected"],
      default: "pending",
    },
    tokenType: { type: String, enum: ["temporary", "permanent"], default: "temporary" },
    tokenExpiry: { type: Date },
  },
  { _id: false }
);

// ---------- SMS ----------
const SmsCredentialSchema = new Schema(
  {
    provider: { type: String, enum: ["twilio", "aws_sns", "vonage", "msg91"], required: true },

    accountSid: { type: String, trim: true }, // Twilio Account SID
    apiKey: secretField, // Vonage API key holder, MSG91 authkey holder (see below)
    authToken: secretField, // Twilio auth token / Vonage API secret

    accessKeyId: secretField, // AWS SNS
    secretAccessKey: secretField, // AWS SNS
    region: { type: String },

    fromNumber: { type: String, trim: true },
    senderId: { type: String, trim: true },

    dlt: {
      entityId: { type: String, trim: true },
      templateId: { type: String, trim: true },
    },
  },
  { _id: false }
);

// ---------- AI PROVIDER (LLM) ----------
const AiProviderCredentialSchema = new Schema(
  {
    provider: {
      type: String,
      enum: [
        "openai",
        "azure_openai",
        "anthropic",
        "google",
        "vertex_ai",
        "cohere",
        "mistral",
        "groq",
        "openrouter",
        "ollama",
        "other",
      ],
      required: true,
    },

    apiKey: secretField,
    baseUrl: { type: String, trim: true },

    orgId: { type: String, trim: true },
    projectId: { type: String, trim: true },

    deploymentName: { type: String, trim: true },
    apiVersion: { type: String, trim: true },

    serviceAccountJson: secretField, // Google Vertex AI
    gcpProjectId: { type: String, trim: true },
    region: { type: String, trim: true },

    defaultModel: { type: String, trim: true },

    usage: {
      totalTokensUsed: { type: Number, default: 0 },
      totalCostUsd: { type: Number, default: 0 },
      lastUsedAt: { type: Date },
    },
  },
  { _id: false }
);

// One connected/created spreadsheet under an OAuth-connected Google account.
// A single Google account can power many bots, each pointed at a different
// sheet — so this lives in an array on the credential, not a single field.
const GoogleSheetEntrySchema = new Schema(
  {
    label: { type: String, trim: true }, // editable in the UI — "Main store", "Safari bookings", etc.
    spreadsheetId: { type: String, trim: true, required: true },
    spreadsheetUrl: { type: String, trim: true },
    tabsInitialized: { type: Boolean, default: false },
    connectedAt: { type: Date, default: Date.now },
  },
  { _id: true }
);

// ---------- GOOGLE SHEETS (unified tools data layer — Items/Availability/
// Orders/Users/Payments/Tickets tabs, see services/googleSheets.service.js) ----------
const GoogleSheetsCredentialSchema = new Schema(
  {
    // "oauth" (recommended — the same "Connect Google" flow/credential as
    // Email; one Google account, any number of sheets underneath it) or
    // "service_account" (advanced/legacy — paste a GCP service account JSON
    // key and share one sheet with it; one credential = one sheet).
    method: { type: String, enum: ["oauth", "service_account"], default: "oauth" },

    // --- method: "oauth" ---
    oauth: {
      email: { type: String, trim: true, lowercase: true }, // which Google account was connected
      accessToken: secretField,
      refreshToken: secretField,
      tokenExpiry: { type: Date },
    },
    // Every spreadsheet this Google account has created/attached through us.
    // A bot picks one entry's spreadsheetId (Bot.toolsConfig.spreadsheetId)
    // — the credential itself just holds the shared OAuth tokens.
    sheets: [GoogleSheetEntrySchema],

    // --- method: "service_account" ---
    // Google service-account JSON key (downloaded from GCP console). Must be
    // shared as an Editor on the target Sheet. One credential = one sheet —
    // for more, add another service-account credential. Stored encrypted;
    // the bot backend exchanges it for a short-lived OAuth2 access token per
    // request (see googleSheets.service.js#getAccessToken) — never
    // stored/reused raw.
    spreadsheetId: { type: String, trim: true },
    spreadsheetUrl: { type: String, trim: true },
    serviceAccountJson: secretField,
    serviceAccountEmail: { type: String, trim: true }, // parsed out of the JSON, shown in the UI as "share the sheet with this address"
    tabsInitialized: { type: Boolean, default: false },
  },
  { _id: false }
);

// ---------- RAZORPAY (per-bot real payments — Payment Links + refunds) ----------
const RazorpayCredentialSchema = new Schema(
  {
    keyId: { type: String, trim: true, required: true }, // not secret — safe to echo back, needed client-side for some flows
    keySecret: secretField,
    // Optional — only needed if/when a webhook is configured on this account
    // for real-time payment confirmation (see razorpay.service.js).
    webhookSecret: secretField,
  },
  { _id: false }
);

// ---------- MEETING SCHEDULING (1-on-1 meeting bookings — Google Meet /
// Cal.com / Calendly, see services/meetingProviders.service.js) ----------
// One credential = one provider account. The bot's per-mentor scheduling
// config (which item_id uses which provider, host email, event type, etc.)
// still lives on the connected Google Sheet's "Mentors" tab, same spirit as
// Items/Availability — this credential only holds the secret needed to
// actually talk to that provider's API.
const MeetingSchedulingCredentialSchema = new Schema(
  {
    provider: { type: String, enum: ["google_meet", "cal_com", "calendly"], required: true },

    // --- google_meet ---
    // Same "Connect Google" OAuth flow/credential as Email and Google
    // Sheets — one sign-in, one consent screen (now also asking for the
    // calendar.events scope, see config/oauthProviders.js) creates all
    // three at once. Meetings are created directly on the connected
    // account's own calendar via the Calendar API, so there's no separate
    // service-account key to manage or calendar to manually share.
    googleMeet: {
      email: { type: String, trim: true, lowercase: true }, // which Google account was connected
      accessToken: secretField,
      refreshToken: secretField,
      tokenExpiry: { type: Date },
      calendarId: { type: String, trim: true, default: "primary" },
      defaultTimezone: { type: String, trim: true, default: "Asia/Kolkata" },
    },

    // --- cal_com ---
    // Cal.com API key (Settings → Developer → API Keys). We create real
    // bookings against a specific event type via their public API.
    calCom: {
      apiKey: secretField,
      baseUrl: { type: String, trim: true, default: "https://api.cal.com" },
      username: { type: String, trim: true }, // cal.com/<username>
    },

    // --- calendly ---
    // Calendly's public API doesn't support creating a booking on behalf of
    // an invitee (only reading events/invitees), so for this provider we
    // hand the customer a real Calendly scheduling link (pre-filled with
    // their name/email) instead of booking the slot ourselves — the
    // Personal Access Token is only used to verify the connection and look
    // up the account's scheduling URL.
    calendly: {
      apiToken: secretField,
      organizationUri: { type: String, trim: true },
      schedulingBaseUrl: { type: String, trim: true }, // e.g. https://calendly.com/your-handle
    },
  },
  { _id: false }
);

const IntegrationCredentialSchema = new Schema(
  {
    user: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },

    channel: {
      type: String,
      enum: ["email", "whatsapp", "sms", "ai_provider", "google_sheets", "razorpay", "meeting_scheduling"],
      required: true,
      index: true,
    },

    label: { type: String, trim: true }, // e.g. "Support Inbox", "Main WhatsApp"

    isDefault: { type: Boolean, default: false },
    isActive: { type: Boolean, default: true },

    email: EmailCredentialSchema,
    whatsapp: WhatsappCredentialSchema,
    sms: SmsCredentialSchema,
    aiProvider: AiProviderCredentialSchema,
    googleSheets: GoogleSheetsCredentialSchema,
    razorpay: RazorpayCredentialSchema,
    meetingScheduling: MeetingSchedulingCredentialSchema,

    status: {
      type: String,
      enum: ["unverified", "connected", "failed", "expired"],
      default: "unverified",
    },
    lastCheckedAt: { type: Date },
    lastError: { type: String },
  },
  {
    timestamps: true,
    toJSON: { getters: true },
    toObject: { getters: true },
  }
);

IntegrationCredentialSchema.pre("validate", function (next) {
  const channelFieldMap = {
    email: "email",
    whatsapp: "whatsapp",
    sms: "sms",
    ai_provider: "aiProvider",
    google_sheets: "googleSheets",
    razorpay: "razorpay",
    meeting_scheduling: "meetingScheduling",
  };
  const requiredField = channelFieldMap[this.channel];
  if (!this[requiredField]) {
    return next(new Error(`Missing "${requiredField}" data for channel "${this.channel}"`));
  }

  // appId/appSecret are only pasted by hand on the "manual" WhatsApp path —
  // "embedded" signups use our own shared Meta App and have those two
  // fields filled in programmatically (see whatsappEmbeddedSignup.service.js),
  // never by the tenant.
  if (this.channel === "whatsapp" && this.whatsapp?.signupMethod !== "embedded") {
    if (!this.whatsapp?.appId || !this.whatsapp?.appSecret) {
      return next(new Error("appId and appSecret are required for a manually-connected WhatsApp number"));
    }
  }

  next();
});

// Only one default credential per channel per user (enforced in service layer via
// unsetting previous defaults, kept non-unique here since isDefault is usually false).
IntegrationCredentialSchema.index({ user: 1, channel: 1, isDefault: 1 });

IntegrationCredentialSchema.methods.markVerified = function () {
  this.status = "connected";
  this.lastCheckedAt = new Date();
  this.lastError = undefined;
  return this.save();
};

IntegrationCredentialSchema.methods.markFailed = function (errorMessage) {
  this.status = "failed";
  this.lastCheckedAt = new Date();
  this.lastError = String(errorMessage || "Connection test failed").slice(0, 500);
  return this.save();
};

module.exports = mongoose.model("IntegrationCredential", IntegrationCredentialSchema);